version: '3.7'
services:
    web:
        container_name: "nginx-nuxgame"
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html:ro"
        ports:
            - "8000:80"
        environment:
            NGINX_HOST: ${NGINX_HOST}
        restart: always
        depends_on:
            - php
    php:
        container_name: "php-nuxgame"
        build:
            context: ./
            dockerfile: ./etc/php/Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
            - "tmp-cache:/var/www/html/bootstrap/cache"
            - "tmp-storage:/var/www/html/storage"
        env_file:
            - ./.env
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: 5432
            DB_DATABASE: ${POSTGRES_DATABASE}
            DB_USERNAME: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
    pg:
        container_name: "pg-nuxgame"
        image: postgres:${POSTGRES_VERSION}
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}

volumes:
    pgdata:
    tmp-cache:
    tmp-storage:
